services:
  postgres:
    image: postgres:17
    container_name: "${APP_NAME}_POSTGRES_${NODE_ENV}"
    restart: unless-stopped
    env_file:
      - "${ENV_FILE}"
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ${NODE_ENV}-network

  redis:
    image: redis:7.2
    container_name: "${APP_NAME}_REDIS_${NODE_ENV}"
    restart: unless-stopped
    env_file:
      - "${ENV_FILE}"
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - ${NODE_ENV}-network

  backend-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: "${APP_NAME}_APP_DEV"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - "${ENV_FILE}"
    command: ["npm","run","start:dev"]
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - dev-network
    profiles:
      - dev

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: "${APP_NAME}_backend_prod"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - "${ENV_FILE}"
    command: ["sh","-c","npm run migrate:prod && npm run start:prod"]
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_PORT}"
    networks:
      - prod-network
    profiles:
      - prod

  db-backup:
    image: postgres:17
    container_name: "${APP_NAME}_DB_BACKUP"
    depends_on:
      - postgres
    env_file:
      - "${ENV_FILE}"
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    volumes:
      - backups:/backups
      - ./docker/postgres-backup/backup.sh:/backup.sh
    entrypoint:
      - sh
      - -c
      - |
        while true; do
          /backup.sh
          sleep 86400
        done
    networks:
      - prod-network
    profiles:
      - prod

networks:
  dev-network:
    driver: bridge
  prod-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  node_modules:
  backups:
